resolver: lts-15.11
allow-newer: true
flags:
  generic-deriving:
    base-4-9: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
#- bloodhound-0.16.0.0
- git: https://github.com/wireapp/bloodhound # fork attempting to support ghc 8.8
  commit: b409f52b518f20a4c20651b5893c31b7b85cb9b1
- snap-1.1.3.0
- heist-1.1.0.1
- map-syntax-0.3
- pwstore-fast-2.4.4
- xmlhtml-0.2.5.2
